language: node_js
node_js:
  - "node"
script:
  - npm test
  - npm run cover
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - master
    - dev
    - next